#line 2 "pplex.c"

#line 4 "pplex.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer pp_create_buffer
#define yy_delete_buffer pp_delete_buffer
#define yy_flex_debug pp_flex_debug
#define yy_init_buffer pp_init_buffer
#define yy_flush_buffer pp_flush_buffer
#define yy_load_buffer_state pp_load_buffer_state
#define yy_switch_to_buffer pp_switch_to_buffer
#define yyin ppin
#define yyleng ppleng
#define yylex pplex
#define yylineno pplineno
#define yyout ppout
#define yyrestart pprestart
#define yytext pptext
#define yywrap ppwrap
#define yyalloc ppalloc
#define yyrealloc pprealloc
#define yyfree ppfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE pprestart(ppin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int ppleng;

extern FILE *ppin, *ppout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pptext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up pptext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via pprestart()), so that the user can continue scanning by
	 * just pointing ppin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when pptext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int ppleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow ppwrap()'s to do buffer switches
 * instead of setting up a fresh ppin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void pprestart (FILE *input_file  );
void pp_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE pp_create_buffer (FILE *file,int size  );
void pp_delete_buffer (YY_BUFFER_STATE b  );
void pp_flush_buffer (YY_BUFFER_STATE b  );
void pppush_buffer_state (YY_BUFFER_STATE new_buffer  );
void pppop_buffer_state (void );

static void ppensure_buffer_stack (void );
static void pp_load_buffer_state (void );
static void pp_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER pp_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE pp_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE pp_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE pp_scan_bytes (yyconst char *bytes,int len  );

void *ppalloc (yy_size_t  );
void *pprealloc (void *,yy_size_t  );
void ppfree (void *  );

#define yy_new_buffer pp_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        ppensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pp_create_buffer(ppin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        ppensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            pp_create_buffer(ppin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define ppwrap(n) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *ppin = (FILE *) 0, *ppout = (FILE *) 0;

typedef int yy_state_type;

extern int pplineno;

int pplineno = 1;

extern char *pptext;
#define yytext_ptr pptext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up pptext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	ppleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 54
#define YY_END_OF_BUFFER 55
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[246] =
    {   0,
        0,    0,    6,    6,    0,    0,    0,    0,   55,   53,
       45,   46,   53,   53,   48,   49,   53,   53,   53,   50,
       53,   50,   53,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   53,    2,    3,    6,    5,    6,    2,    3,
       26,   10,   11,   26,   26,   14,   15,   26,   26,   26,
       23,   12,   23,   26,   26,   23,   23,   23,   23,   23,
       23,   23,   26,    2,    3,   33,   27,   28,   33,   33,
       33,   33,   33,   30,   33,   30,   33,   33,   30,   33,
        2,    3,   46,    0,   52,    0,    1,    0,   51,   45,
       47,   50,   50,    0,   46,   50,   50,   50,   50,   50,

       50,   50,   50,   50,    2,    1,    3,    6,    1,    2,
        1,    3,   11,    0,   25,    0,    0,   24,   10,   23,
       23,    0,   13,   16,   17,   18,   23,   23,   23,   28,
        0,   32,    0,    0,   31,   27,   30,   30,    0,   29,
        1,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,    1,    1,    1,   19,   23,   23,   23,   50,
        7,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       23,   23,   23,   50,   50,   41,   50,   50,   50,   50,
       50,   50,   42,   43,   44,   23,   23,   23,   34,   50,
       50,   50,   41,   50,   50,   50,   50,   50,   50,   42,

       43,   44,   23,   23,   23,   50,   50,   50,    8,   50,
        4,   39,    9,   50,   23,   23,   23,   50,   50,   50,
       50,   40,   21,   23,   20,   50,   50,   50,   50,   22,
       50,   50,   50,   50,   50,   50,   50,   50,   50,   50,
       35,   38,   37,   36,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    1,    4,    1,    1,    1,    1,    5,    6,
        7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
       17,   14,   14,   14,   14,   14,   14,    1,   18,    1,
       19,   20,    1,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   38,   43,   38,   44,   38,
       21,   21,   21,   21,   38,   21,   45,   46,   47,   48,

       49,   50,   51,   52,   53,   54,   55,   56,   57,   58,
       59,   60,   38,   61,   62,   63,   64,   38,   65,   38,
       66,   38,   21,   21,   21,   21,    1,   21,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,

       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   68,   68,   68,   68,   68,   68,   68,
       68,   68,   68,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,   67,   67,   67,   67,   67,   67,   67,   67,
       67,   67,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[69] =
    {   0,
        1,    2,    1,    1,    1,    1,    1,    1,    1,    3,
        3,    3,    1,    3,    3,    3,    3,    1,    1,    1,
        1,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3
    } ;

static yyconst flex_int16_t yy_base[266] =
    {   0,
        0,   61,   68,   69,   82,   65,  150,  217,  314, 1313,
     1313,  308,  305,  298, 1313, 1313,  280,  162,  178,  186,
      194,  229,   77,  230,  187,  239,  238,  245,  246,  249,
      252,  253,  311,  275,    0,    0, 1313,  272,  270,    0,
     1313, 1313,  286,  283,  281, 1313, 1313,  262,  319,  335,
      343,  351,  359,  180,  261,  202,  334,  329,  367,  344,
      281,  360,  374,  257,    0, 1313, 1313,  271,  269,  266,
      248,  404,  426,  434,  442,  450,  182,  248,  203,  458,
      246,    0,  249,  243, 1313,  211,    0,  466,  474, 1313,
      204,  330,  482,  492,  202,  475,  370,  483,  396,  508,

      500,  517,  509,  513,    0,    0,    0,    0,    0,    0,
        0,    0,  188,  185, 1313,  182,  548,  571, 1313,  525,
      579,  587, 1313,  559,  595,  600,  599,  603,  604,  183,
      171, 1313,  168,  607,  618, 1313,  608,  639,  662, 1313,
        0,  632,  647,  670,  676,  648,  627,  677,  683,  697,
      698,  708,    0,    0,    0,  635,  719,  715,  723,  722,
      726,  745,  729,  737,  762,  768,  749,  775,  788,  809,
      793,  796,  801,  818,  827,  821,  833,  826,  840,  834,
      859,  865,  855,  886,  887,  893,  900,  899,  903,  904,
      909,  917, 1313,  923,  918,  924,  940,  932,  947, 1313,

     1313, 1313,  963,  967,  977,  984,  983,  993,  994, 1003,
      999, 1012, 1016, 1023, 1017, 1028, 1037, 1043, 1044, 1052,
     1059, 1047, 1063, 1066, 1075, 1086, 1096, 1095, 1108, 1115,
     1122, 1119, 1125, 1131, 1138, 1142, 1135, 1159, 1171, 1185,
     1147, 1167, 1189, 1194, 1313, 1261, 1264, 1267, 1270,   78,
     1273, 1276, 1279, 1282, 1285, 1288, 1291,   72, 1294, 1297,
       69, 1300, 1303, 1306, 1309
    } ;

static yyconst flex_int16_t yy_def[266] =
    {   0,
      245,    1,  246,  246,  245,    5,  247,  247,  245,  245,
      245,  245,  248,  249,  245,  245,  245,  245,  245,  250,
      245,  250,  245,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  251,  252,  253,  245,  253,  254,  255,
      245,  245,  245,  256,  257,  245,  245,  245,  245,  245,
      258,  245,  258,  245,  245,  258,  258,  258,  258,  258,
      258,  258,  258,  251,  252,  245,  245,  245,  259,  260,
      245,  245,  245,  261,  245,  261,  245,  245,  261,  261,
      251,  252,  245,  248,  245,  249,  262,  245,  245,  245,
      245,  250,  250,  250,  245,  250,  250,  250,  250,  250,

      250,  250,  250,  250,  251,  263,  252,  253,  264,  254,
      265,  255,  245,  256,  245,  257,  245,  245,  245,  258,
      258,  258,  245,  258,  258,  258,  258,  258,  258,  245,
      259,  245,  260,  245,  245,  245,  261,  261,  261,  245,
      262,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  263,  264,  265,  258,  258,  258,  258,  250,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      258,  258,  258,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  250,  258,  258,  258,  250,  250,
      250,  250,  245,  250,  250,  250,  250,  250,  250,  245,

      245,  245,  258,  258,  258,  250,  250,  250,  250,  250,
      250,  250,  250,  250,  258,  258,  258,  250,  250,  250,
      250,  250,  258,  258,  258,  250,  250,  250,  250,  258,
      250,  250,  250,  250,  250,  250,  250,  250,  250,  250,
      250,  250,  250,  250,    0,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245
    } ;

static yyconst flex_int16_t yy_nxt[1382] =
    {   0,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   10,   22,   22,   22,   22,   23,   10,   10,
       10,   24,   25,   26,   27,   28,   25,   25,   25,   29,
       25,   25,   25,   25,   25,   25,   30,   25,   31,   32,
       25,   25,   25,   25,   24,   25,   26,   27,   28,   25,
       25,   25,   29,   25,   25,   25,   25,   25,   25,   30,
       31,   32,   25,   25,   25,   25,   33,   25,   34,   37,
       37,  137,   64,   35,  120,   38,   39,   65,   90,   95,
       92,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   50,   51,   52,   41,   53,   53,   53,   53,   54,

       55,   41,   41,   56,   57,   56,   56,   56,   56,   56,
       56,   58,   56,   56,   56,   56,   56,   59,   60,   56,
       61,   62,   56,   56,   56,   56,   56,   57,   56,   56,
       56,   56,   56,   56,   58,   56,   56,   56,   56,   56,
       59,   60,   61,   62,   56,   56,   56,   56,   63,   56,
       66,   67,   68,   69,   70,   66,   66,   71,   72,   73,
       74,   75,   66,   76,   76,   76,   76,   77,   78,   66,
       66,   88,  132,   88,  132,   89,   89,   89,   89,   90,
       91,  119,  113,  136,  130,  130,  115,   88,  115,   88,
      113,   89,   89,   89,   89,   88,  245,   88,  245,   93,

       93,   93,   93,   88,   95,   88,   91,   89,   89,   89,
       89,  245,  245,  245,  245,   85,   80,   66,   67,   68,
       69,   70,   66,   66,   81,   72,   73,   74,   75,   82,
       76,   76,   76,   76,   77,   78,   66,   66,   88,  245,
       88,  245,   93,   93,   93,   93,   85,  245,  245,  245,
      245,   83,   94,   94,  245,  245,  245,  245,  245,   98,
      245,  245,  245,  245,  245,  106,  140,   87,  122,  139,
      132,   96,  132,  130,   97,   99,  106,  102,  103,  123,
      100,   87,   98,   80,  104,  115,  115,  101,  113,  111,
      245,  109,  245,   96,  106,   94,   94,   97,   99,   87,

      102,  103,   85,  100,   94,   94,  128,  104,   85,  101,
       83,   94,   94,  245,  245,   94,  245,  245,   94,   94,
      245,  245,  245,  245,  245,  245,  245,  245,  117,  128,
      117,   92,  118,  118,  118,  118,  119,  113,  245,  245,
      245,  245,  245,  245,  117,  245,  117,  122,  118,  118,
      118,  118,  117,  245,  117,  245,  121,  121,  121,  121,
      117,  245,  117,  125,  118,  118,  118,  118,  117,  245,
      117,  245,  121,  121,  121,  121,  245,  124,  245,  245,
      245,  245,  127,  245,  245,  245,  125,  245,  245,  245,
      245,  245,  245,  126,  120,  122,   94,  245,  245,  124,

      122,  129,  245,  245,  127,  245,  143,  245,  245,  122,
      122,  245,  245,  134,  245,  134,  126,  135,  135,  135,
      135,  145,  245,  129,  245,  122,  122,  136,  130,  143,
      245,  245,  245,  122,  245,  134,   94,  134,  245,  135,
      135,  135,  135,  134,  145,  134,  245,  138,  138,  138,
      138,  134,  245,  134,  245,  135,  135,  135,  135,  134,
      245,  134,   94,  138,  138,  138,  138,  245,  245,  245,
      245,  245,  245,  245,  245,   88,  245,   88,  137,   89,
       89,   89,   89,   88,  245,   88,  245,   89,   89,   89,
       89,   88,  245,   88,  245,   93,   93,   93,   93,  245,

      139,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,   92,  245,  245,  142,  139,  245,  245,  245,
      245,  245,  245,  144,  245,  245,  245,  245,  245,  245,
      245,  146,  151,  245,  245,  148,  245,  142,  245,  245,
      245,   94,  152,  245,  245,  144,  245,  147,   94,   94,
      149,  245,  245,  150,  146,  151,  245,  117,  148,  117,
      245,  118,  118,  118,  118,  152,   94,  245,  245,  147,
      245,  245,  245,  149,   94,   94,  150,  245,  245,   94,
      117,  245,  117,   94,  118,  118,  118,  118,  117,  245,
      117,  122,  121,  121,  121,  121,  245,  245,  245,  245,

      245,  245,  245,  245,  245,  245,  245,  120,  245,  245,
      245,  245,  245,  245,  245,  245,  134,  245,  134,  245,
      135,  135,  135,  135,  245,  122,  156,  134,  157,  134,
      245,  135,  135,  135,  135,  245,  245,  245,  245,  158,
      159,  245,  245,  245,  245,  122,  245,  245,  134,  156,
      134,  157,  138,  138,  138,  138,  245,  245,  245,  245,
      160,  122,  158,  159,  245,  122,  122,  165,  245,  122,
      122,  245,  245,  245,  139,  245,  245,  245,  245,  245,
      164,  245,  137,  160,  245,  245,  245,  245,  245,  165,
      161,  245,  245,   94,  245,  162,  245,  245,   94,  163,

      166,  122,  245,  164,  167,  139,  245,  245,  245,  245,
      245,  245,  161,   94,   94,  245,  245,  245,  162,  245,
      245,  245,  163,  166,  245,  245,  245,  167,  245,  168,
      245,  245,  245,  245,  245,  245,   94,  245,  245,  169,
      245,  245,   94,   94,  170,  245,  245,  172,  245,   94,
      245,  245,  168,  171,  245,  175,  245,  174,  245,  173,
      245,  169,  245,   94,   94,  245,  245,  170,  245,  176,
      172,  245,  245,  245,   94,  245,  171,  245,  177,  245,
      174,  122,  173,  178,  245,  122,  245,  180,   94,  122,
      245,  176,   94,  179,  245,   94,  181,  245,  245,  245,

      177,  245,  245,   94,  245,  245,  178,  245,  245,  180,
      245,   94,  245,  245,  245,   94,  179,  187,  245,  181,
      245,  245,  245,  183,  184,  185,  182,  245,   94,  245,
      245,  245,  193,  186,   94,  245,  245,  245,  245,  188,
      187,   94,  245,  245,  245,  245,  245,  245,  182,  245,
      190,  245,  245,  245,   94,  186,  189,  194,  195,  122,
      191,  188,  122,  245,  245,  197,  200,  122,  245,  192,
      245,  245,  245,  190,  245,   94,  245,  245,  189,  196,
      194,  195,  198,  191,   94,  245,  245,   94,  197,  245,
      245,  192,   94,   94,  199,  245,  245,  201,  202,   94,

       94,  196,  245,  245,  245,  198,   94,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  199,  245,  245,
      245,   94,  203,  204,  205,   94,  245,  245,  245,  245,
      245,   94,  245,  245,  245,  245,  245,  245,  245,  206,
      245,  245,  245,  245,  207,  203,  204,  205,  209,  245,
      210,  245,   94,   94,  245,  208,  245,  213,  245,  122,
      245,  245,  206,  211,  245,  122,  122,  207,  245,   94,
       94,  209,  245,  210,  245,   94,  245,  208,  245,  212,
      213,  245,  245,   94,   94,  211,  245,  214,  245,   94,
       94,  245,  245,  245,  245,  245,  216,  215,   94,  245,

      245,  212,  245,  245,  245,  245,   94,  219,  245,  214,
      245,  245,  245,   94,  245,  245,  217,  218,  245,  216,
      215,  245,  220,  245,  221,  245,  245,  245,  245,  122,
      219,  245,  245,  122,  245,  245,  245,  245,  217,  245,
      218,  245,  245,  122,  223,  220,  245,  221,  245,   94,
       94,  245,  245,  245,  245,  245,  245,  245,  245,   94,
       94,  245,  224,  245,  245,   94,  222,  223,  245,   94,
      245,  245,  245,  227,  245,  245,  225,  245,   94,  226,
      245,  245,   94,  122,  245,  224,  245,  245,  222,   94,
      245,  245,  228,  230,  122,  245,  227,  245,  225,  229,

      245,  245,  226,  122,  245,  245,  245,  245,  245,   94,
       94,  245,  245,   94,  228,  231,  230,  245,   94,  245,
      245,  229,  232,  245,  245,   94,  245,  245,  245,  122,
      245,  245,  122,  245,  245,  233,  245,  234,  231,  245,
      245,  122,  245,  245,  245,  232,  245,  245,  236,  245,
      237,  245,   94,  245,  235,  245,  245,  233,  245,  245,
      234,   94,   94,  239,  245,  245,  238,  240,  245,  241,
      245,  236,  245,  237,   94,  245,  245,  235,  245,  245,
      245,  122,  245,  245,  245,   94,  239,  245,   94,  238,
      240,   94,  241,  242,  245,  243,  245,   94,  245,  245,

      245,   94,  245,  245,   94,  245,  245,  245,   94,  244,
      245,  245,  245,   94,  245,  245,  242,  245,  243,  245,
      245,  245,  245,  245,  245,   94,  245,  245,  245,  245,
      245,  245,  244,   94,  245,  245,  245,   94,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,   94,  245,  245,  245,   94,  245,  245,  245,  245,
       94,   36,   36,   36,   79,   79,   79,   84,  245,   84,
       86,  245,   86,  105,  245,  105,  107,  245,  107,  108,
      245,  108,  110,  245,  110,  112,  245,  112,  114,  245,
      114,  116,  245,  116,  131,  245,  131,  133,  245,  133,

      141,  245,  141,  153,  245,  153,  154,  245,  154,  155,
      245,  155,    9,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245
    } ;

static yyconst flex_int16_t yy_chk[1382] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        4,  261,    6,    2,  258,    3,    4,    6,   23,   23,
      250,    4,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,   18,  133,   18,  131,   18,   18,   18,   18,   19,
       19,   54,   54,   77,   77,  130,  116,   19,  114,   19,
      113,   19,   19,   19,   19,   20,   25,   20,   25,   20,

       20,   20,   20,   21,   95,   21,   91,   21,   21,   21,
       21,   56,   79,   56,   79,   86,    7,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,   22,   24,
       22,   24,   22,   22,   22,   22,   84,   27,   26,   27,
       26,   83,   20,   25,   28,   29,   28,   29,   30,   27,
       30,   31,   32,   31,   32,   81,   78,   71,   56,   79,
       70,   24,   69,   68,   26,   28,   64,   31,   32,   55,
       29,   48,   27,    8,   32,   45,   44,   30,   43,   39,
       61,   38,   61,   24,   34,   22,   24,   26,   28,   17,

       31,   32,   14,   29,   27,   26,   61,   32,   13,   30,
       12,   28,   29,    9,    0,   30,    0,    0,   31,   32,
       33,   33,   33,    0,   33,   33,   33,   33,   49,   61,
       49,   33,   49,   49,   49,   49,   50,   50,   58,   92,
       58,   92,    0,   57,   50,   57,   50,   61,   50,   50,
       50,   50,   51,   60,   51,   60,   51,   51,   51,   51,
       52,    0,   52,   58,   52,   52,   52,   52,   53,   62,
       53,   62,   53,   53,   53,   53,   59,   57,   59,   97,
        0,   97,   60,   63,   63,   63,   58,   63,   63,   63,
       63,    0,    0,   59,   63,   58,   92,    0,    0,   57,

       57,   62,    0,    0,   60,   99,   97,   99,    0,   51,
       60,    0,    0,   72,    0,   72,   59,   72,   72,   72,
       72,   99,    0,   62,    0,   53,   62,   73,   73,   97,
        0,    0,    0,   59,    0,   73,   97,   73,    0,   73,
       73,   73,   73,   74,   99,   74,    0,   74,   74,   74,
       74,   75,    0,   75,    0,   75,   75,   75,   75,   76,
        0,   76,   99,   76,   76,   76,   76,   80,   80,   80,
        0,   80,   80,   80,   80,   88,    0,   88,   80,   88,
       88,   88,   88,   89,   96,   89,   96,   89,   89,   89,
       89,   93,   98,   93,   98,   93,   93,   93,   93,    0,

       74,   94,   94,   94,    0,   94,   94,   94,   94,  101,
        0,  101,   94,    0,    0,   96,   76,  100,  103,  100,
      103,    0,  104,   98,  104,    0,  102,    0,  102,    0,
        0,  100,  103,    0,  120,  101,  120,   96,    0,    0,
        0,   96,  104,    0,    0,   98,    0,  100,   93,   98,
      102,    0,    0,  102,  100,  103,    0,  117,  101,  117,
        0,  117,  117,  117,  117,  104,  101,    0,  124,  100,
      124,    0,    0,  102,  100,  103,  102,    0,    0,  104,
      118,    0,  118,  102,  118,  118,  118,  118,  121,    0,
      121,  120,  121,  121,  121,  121,  122,  122,  122,    0,

      122,  122,  122,  122,  125,    0,  125,  122,  127,  126,
      127,  126,  128,  129,  128,  129,  134,  137,  134,  137,
      134,  134,  134,  134,    0,  124,  126,  135,  127,  135,
        0,  135,  135,  135,  135,    0,  147,    0,  147,  128,
      129,  142,    0,  142,  156,  121,  156,    0,  138,  126,
      138,  127,  138,  138,  138,  138,  143,  146,  143,  146,
      142,  125,  128,  129,    0,  127,  126,  147,    0,  128,
      129,  139,  139,  139,  137,  139,  139,  139,  139,  144,
      146,  144,  139,  142,    0,  145,  148,  145,  148,  147,
      143,    0,  149,  147,  149,  144,    0,    0,  142,  145,

      148,  156,    0,  146,  149,  138,  150,  151,  150,  151,
        0,    0,  143,  143,  146,    0,    0,  152,  144,  152,
        0,    0,  145,  148,  158,    0,  158,  149,  157,  150,
      157,  160,  159,  160,  159,  161,  144,  161,  163,  151,
      163,    0,  145,  148,  152,    0,  164,  158,  164,  149,
        0,    0,  150,  157,  162,  162,  162,  160,  167,  159,
      167,  151,    0,  150,  151,    0,    0,  152,    0,  163,
      158,  165,    0,  165,  152,    0,  157,  166,  164,  166,
      160,  158,  159,  165,  168,  157,  168,  167,  160,  159,
        0,  163,  161,  166,    0,  163,  168,  169,    0,  169,

      164,    0,  171,  164,  171,  172,  165,  172,    0,  167,
      173,  162,  173,    0,    0,  167,  166,  172,  170,  168,
      170,    0,    0,  170,  170,  170,  169,  174,  165,  174,
      176,    0,  176,  171,  166,  178,  175,  178,  175,  173,
      172,  168,  177,  180,  177,  180,    0,    0,  169,  179,
      175,  179,    0,    0,  169,  171,  174,  177,  178,  171,
      175,  173,  172,    0,  183,  180,  183,  173,  181,  175,
      181,    0,    0,  175,  182,  170,  182,    0,  174,  179,
      177,  178,  181,  175,  174,    0,    0,  176,  180,    0,
        0,  175,  178,  175,  182,  184,  185,  184,  185,  177,

      180,  179,  186,    0,  186,  181,  179,    0,  188,  187,
      188,  187,  189,  190,  189,  190,    0,  182,  191,    0,
      191,  183,  186,  187,  188,  181,  192,  195,  192,  195,
        0,  182,  194,  196,  194,  196,    0,    0,    0,  190,
        0,  198,    0,  198,  191,  186,  187,  188,  194,  197,
      195,  197,  184,  185,    0,  192,  199,  198,  199,  186,
        0,    0,  190,  196,    0,  188,  187,  191,    0,  189,
      190,  194,  203,  195,  203,  191,  204,  192,  204,  197,
      198,    0,    0,  192,  195,  196,  205,  199,  205,  194,
      196,    0,  207,  206,  207,  206,  204,  203,  198,    0,

        0,  197,  208,  209,  208,  209,  197,  207,  211,  199,
      211,    0,  210,  199,  210,    0,  205,  206,    0,  204,
      203,  212,  208,  212,  210,  213,  215,  213,  215,  203,
      207,    0,  214,  204,  214,    0,    0,  216,  205,  216,
      206,    0,    0,  205,  215,  208,  217,  210,  217,  207,
      206,    0,  218,  219,  218,  219,  222,    0,  222,  208,
      209,  220,  216,  220,    0,  211,  214,  215,  221,  210,
      221,    0,  223,  219,  223,  224,  217,  224,  212,  218,
        0,    0,  213,  215,  225,  216,  225,    0,  214,  214,
        0,    0,  220,  224,  216,  226,  219,  226,  217,  221,

        0,    0,  218,  217,  228,  227,  228,  227,    0,  218,
      219,    0,    0,  222,  220,  226,  224,  229,  220,  229,
        0,  221,  227,    0,  230,  221,  230,    0,  232,  223,
      232,  231,  224,  231,  233,  228,  233,  229,  226,    0,
      234,  225,  234,    0,  237,  227,  237,  235,  232,  235,
      233,  236,  226,  236,  231,    0,  241,  228,  241,    0,
      229,  228,  227,  235,    0,    0,  234,  236,  238,  237,
      238,  232,    0,  233,  229,    0,  242,  231,  242,    0,
      239,  230,  239,    0,    0,  232,  235,    0,  231,  234,
      236,  233,  237,  238,  240,  239,  240,  234,  243,    0,

      243,  237,    0,  244,  235,  244,    0,    0,  236,  240,
        0,    0,    0,  241,    0,    0,  238,    0,  239,    0,
        0,    0,    0,    0,    0,  238,    0,    0,    0,    0,
        0,    0,  240,  242,    0,    0,    0,  239,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,  240,    0,    0,    0,  243,    0,    0,    0,    0,
      244,  246,  246,  246,  247,  247,  247,  248,    0,  248,
      249,    0,  249,  251,    0,  251,  252,    0,  252,  253,
        0,  253,  254,    0,  254,  255,    0,  255,  256,    0,
      256,  257,    0,  257,  259,    0,  259,  260,    0,  260,

      262,    0,  262,  263,    0,  263,  264,    0,  264,  265,
        0,  265,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245,  245,  245,  245,  245,  245,  245,  245,  245,  245,
      245
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int pp_flex_debug;
int pp_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *pptext;
#line 1 "pplex.l"
/*							-*- c -*-
 * Copyright (C) 2001-2009 Keisuke Nishida
 * Copyright (C) 2007-2009 Roger While
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this software; see the file COPYING.  If not, write to
 * the Free Software Foundation, 51 Franklin Street, Fifth Floor
 * Boston, MA 02110-1301 USA
 */
#line 28 "pplex.l"

#include "config.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#ifdef	HAVE_UNISTD_H
#include <unistd.h>
#endif
#include <ctype.h>
#include <errno.h>
#include <sys/stat.h>
#include <sys/types.h>

#include "cobc.h"
#include "ppparse.h"

static char	*plexbuff1 = NULL;
static char	*plexbuff2 = NULL;
static size_t	newline_count = 0;
static size_t	within_comment = 0;
static size_t	inside_bracket = 0;
static size_t	consecutive_quotation = 0;
static int	quotation_mark = 0;
static int	last_line_1 = -1;
static int	last_line_2 = -1;

static struct cb_replace_list	*current_replace_list = NULL;

static struct cb_text_list	*text_queue = NULL;

static struct copy_info {
	struct copy_info	*next;
	char			*file;
	int			line;
	int			replacing;
	int			quotation_mark;
	YY_BUFFER_STATE		buffer;
} *copy_stack = NULL;

#define YY_INPUT(buf,result,max_size) result = ppinput (buf, max_size);

static int ppinput (char *buf, int max_size);
static void ppecho (const char *text);

static void switch_to_buffer (const int lineno, const char *filename,
			      YY_BUFFER_STATE buffer);


#line 940 "pplex.c"

#define INITIAL 0
#define PROCESS_STATE 1
#define COPY_STATE 2
#define PSEUDO_STATE 3

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int pplex_destroy (void );

int ppget_debug (void );

void ppset_debug (int debug_flag  );

YY_EXTRA_TYPE ppget_extra (void );

void ppset_extra (YY_EXTRA_TYPE user_defined  );

FILE *ppget_in (void );

void ppset_in  (FILE * in_str  );

FILE *ppget_out (void );

void ppset_out  (FILE * out_str  );

int ppget_leng (void );

char *ppget_text (void );

int ppget_lineno (void );

void ppset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int ppwrap (void );
#else
extern int ppwrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( pptext, ppleng, 1, ppout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( ppin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( ppin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, ppin))==0 && ferror(ppin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(ppin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int pplex (void);

#define YY_DECL int pplex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after pptext and ppleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( ppleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(pptext[ppleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 84 "pplex.l"





#line 1139 "pplex.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! ppin )
			ppin = stdin;

		if ( ! ppout )
			ppout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			ppensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				pp_create_buffer(ppin,YY_BUF_SIZE );
		}

		pp_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of pptext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 246 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 245 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 89 "pplex.l"
{
	ppecho (" ");
}
	YY_BREAK
case 2:
#line 94 "pplex.l"
case 3:
YY_RULE_SETUP
#line 94 "pplex.l"
{
	ppecho (" ");
	if (cb_source_format != CB_FORMAT_FIXED) {
		ppecho (pptext);
	}
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 101 "pplex.l"
{ BEGIN PROCESS_STATE; }
	YY_BREAK

case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 104 "pplex.l"
{ BEGIN INITIAL; unput ('\n'); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 105 "pplex.l"
{ cb_warning (_("PROCESS statement is ignored")); }
	YY_BREAK

case 7:
YY_RULE_SETUP
#line 108 "pplex.l"
{ BEGIN COPY_STATE; return COPY; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 109 "pplex.l"
{ BEGIN COPY_STATE; return COPY; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 110 "pplex.l"
{ BEGIN COPY_STATE; return REPLACE; }
	YY_BREAK

case 10:
/* rule 10 can match eol */
YY_RULE_SETUP
#line 113 "pplex.l"
{ ECHO; cb_source_line++; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 114 "pplex.l"
{ /* ignore */ }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 115 "pplex.l"
{ BEGIN INITIAL; return '.'; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 116 "pplex.l"
{ BEGIN PSEUDO_STATE; return EQEQ; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 117 "pplex.l"
{ return '('; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 118 "pplex.l"
{ return ')'; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 119 "pplex.l"
{ return BY; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 120 "pplex.l"
{ return IN; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 121 "pplex.l"
{ return OF; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 122 "pplex.l"
{ return OFF; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 123 "pplex.l"
{ return SUPPRESS; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 124 "pplex.l"
{ return PRINTING; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 125 "pplex.l"
{ return REPLACING; }
	YY_BREAK
case 23:
#line 127 "pplex.l"
case 24:
#line 128 "pplex.l"
case 25:
#line 129 "pplex.l"
case 26:
YY_RULE_SETUP
#line 129 "pplex.l"
{ pplval.s = strdup (pptext); return TOKEN; }
	YY_BREAK


case 27:
/* rule 27 can match eol */
YY_RULE_SETUP
#line 133 "pplex.l"
{ ECHO; cb_source_line++; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 134 "pplex.l"
{ pplval.s = strdup (" "); return TOKEN; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 135 "pplex.l"
{ BEGIN COPY_STATE; return EQEQ; }
	YY_BREAK
case 30:
#line 137 "pplex.l"
case 31:
#line 138 "pplex.l"
case 32:
#line 139 "pplex.l"
case 33:
YY_RULE_SETUP
#line 139 "pplex.l"
{ pplval.s = strdup (pptext); return TOKEN; }
	YY_BREAK

case 34:
#line 143 "pplex.l"
case 35:
#line 144 "pplex.l"
case 36:
#line 145 "pplex.l"
case 37:
#line 146 "pplex.l"
case 38:
#line 147 "pplex.l"
case 39:
#line 148 "pplex.l"
case 40:
YY_RULE_SETUP
#line 148 "pplex.l"
{
	/* these words are treated as comments */
	if (cb_verify (cb_author_paragraph, pptext)) {
		/* skip comments until the end of line */
		int c;

		within_comment = 1;
		while ((c = input ()) != EOF) {
			if (c == '\n') {
				break;
			}
		}
		unput (c);
	}
}
	YY_BREAK
case 41:
#line 165 "pplex.l"
case 42:
#line 166 "pplex.l"
case 43:
#line 167 "pplex.l"
case 44:
YY_RULE_SETUP
#line 167 "pplex.l"
{
	/* these words are comments in IBM COBOL */
	if (cb_verify (cb_eject_statement, pptext)) {
		/* do nothing for now */
	} else {
		ECHO;
	}
}
	YY_BREAK
case 45:
/* rule 45 can match eol */
YY_RULE_SETUP
#line 176 "pplex.l"
{ ppecho ("\n"); cb_source_line++; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 178 "pplex.l"
{ ppecho (" "); }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 180 "pplex.l"
{
	if (inside_bracket) {
		ppecho (", ");
	} else {
		ppecho (" ");
	}
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 188 "pplex.l"
{
	inside_bracket++;
	ppecho ("(");
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 193 "pplex.l"
{
	if (inside_bracket) {
		inside_bracket--;
	}
	ppecho (")");
}
	YY_BREAK
case 50:
#line 201 "pplex.l"
case 51:
#line 202 "pplex.l"
case 52:
#line 203 "pplex.l"
case 53:
YY_RULE_SETUP
#line 203 "pplex.l"
{ ppecho (pptext); }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(PROCESS_STATE):
case YY_STATE_EOF(COPY_STATE):
case YY_STATE_EOF(PSEUDO_STATE):
#line 205 "pplex.l"
{
	struct copy_info *p;

	p = copy_stack;

	pp_delete_buffer (YY_CURRENT_BUFFER);

	/* Terminate at the end of all input */
	if (p->next == NULL) {
		within_comment = 0;
		newline_count = 0;
		inside_bracket = 0;
		current_replace_list = NULL;
		text_queue = NULL;
		copy_stack = NULL;
		quotation_mark = 0;
		consecutive_quotation = 0;
		last_line_1 = -1;
		last_line_2 = -1;
		yyterminate ();
	}

	/* Close the current file */
	fclose (ppin);

	/* Switch to the last buffer */
	if (p->replacing) {
		pp_set_replace_list (NULL);
	}
	switch_to_buffer (p->line, p->file, p->buffer);
	quotation_mark = p->quotation_mark;

	copy_stack = p->next;
	free (p);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 241 "pplex.l"
YY_FATAL_ERROR( "flex scanner jammed" );
	YY_BREAK
#line 1525 "pplex.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed ppin at a new source and called
			 * pplex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = ppin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( ppwrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * pptext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of pplex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					pprealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			pprestart(ppin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) pprealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 246 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 246 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 245);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up pptext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					pprestart(ppin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( ppwrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve pptext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void pprestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        ppensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            pp_create_buffer(ppin,YY_BUF_SIZE );
	}

	pp_init_buffer(YY_CURRENT_BUFFER,input_file );
	pp_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void pp_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		pppop_buffer_state();
	 *		pppush_buffer_state(new_buffer);
     */
	ppensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	pp_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (ppwrap()) processing, but the only time this flag
	 * is looked at is after ppwrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void pp_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	ppin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE pp_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) ppalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pp_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) ppalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in pp_create_buffer()" );

	b->yy_is_our_buffer = 1;

	pp_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with pp_create_buffer()
 * 
 */
    void pp_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		ppfree((void *) b->yy_ch_buf  );

	ppfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a pprestart() or at EOF.
 */
    static void pp_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	pp_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then pp_init_buffer was _probably_
     * called from pprestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void pp_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		pp_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void pppush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	ppensure_buffer_stack();

	/* This block is copied from pp_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from pp_switch_to_buffer. */
	pp_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void pppop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	pp_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		pp_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void ppensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)ppalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ppensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)pprealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in ppensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE pp_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) ppalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in pp_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	pp_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to pplex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       pp_scan_bytes() instead.
 */
YY_BUFFER_STATE pp_scan_string (yyconst char * yystr )
{
    
	return pp_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to pplex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE pp_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) ppalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in pp_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = pp_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in pp_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up pptext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		pptext[ppleng] = (yy_hold_char); \
		(yy_c_buf_p) = pptext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		ppleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int ppget_lineno  (void)
{
        
    return pplineno;
}

/** Get the input stream.
 * 
 */
FILE *ppget_in  (void)
{
        return ppin;
}

/** Get the output stream.
 * 
 */
FILE *ppget_out  (void)
{
        return ppout;
}

/** Get the length of the current token.
 * 
 */
int ppget_leng  (void)
{
        return ppleng;
}

/** Get the current token.
 * 
 */

char *ppget_text  (void)
{
        return pptext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void ppset_lineno (int  line_number )
{
    
    pplineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see pp_switch_to_buffer
 */
void ppset_in (FILE *  in_str )
{
        ppin = in_str ;
}

void ppset_out (FILE *  out_str )
{
        ppout = out_str ;
}

int ppget_debug  (void)
{
        return pp_flex_debug;
}

void ppset_debug (int  bdebug )
{
        pp_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from pplex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    ppin = stdin;
    ppout = stdout;
#else
    ppin = (FILE *) 0;
    ppout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * pplex_init()
     */
    return 0;
}

/* pplex_destroy is for both reentrant and non-reentrant scanners. */
int pplex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		pp_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		pppop_buffer_state();
	}

	/* Destroy the stack itself. */
	ppfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * pplex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *ppalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *pprealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void ppfree (void * ptr )
{
	free( (char *) ptr );	/* see pprealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 241 "pplex.l"



void
pp_set_replace_list (struct cb_replace_list *list)
{
	current_replace_list = list;
}

static void
switch_to_buffer (const int line, const char *file, YY_BUFFER_STATE buffer)
{
	char	*p;

	cb_source_line = line;
	cb_source_file = strdup (file);
	for (p = cb_source_file; *p; p++) {
		if (*p == '\\') {
			*p = '/';
		}
	}
	pp_switch_to_buffer (buffer);
	fprintf (ppout, "# %d \"%s\"\n", line, cb_source_file);
}

int
ppopen (const char *name, struct cb_replace_list *replace_list)
{
	struct copy_info *p;

	for (; newline_count > 0; newline_count--) {
		ungetc ('\n', ppin);
	}

	/* Open the copy file */
	ppin = fopen (name, "rb");
	if (!ppin) {
		if (cb_source_file) {
			cb_error (_("%s: %s"), name, strerror (errno));
		} else {
			perror (name);
		}
		return -1;
	}

	/* Add to dependency list */
	if (cb_depend_file) {
		cb_depend_list = cb_text_list_add (cb_depend_list, name);
	}

	/* Preserve the current buffer */
	p = cobc_malloc (sizeof (struct copy_info));
	p->line = cb_source_line;
	p->file = cb_source_file;
	p->replacing = replace_list ? 1 : 0;
	p->buffer = YY_CURRENT_BUFFER;
	p->quotation_mark = quotation_mark;
	p->next = copy_stack;
	copy_stack = p;

	/* Switch to new buffer */
	if (replace_list) {
		pp_set_replace_list (replace_list);
	}
	switch_to_buffer (1, name, pp_create_buffer (ppin, YY_BUF_SIZE));
	return 0;
}

int
ppcopy (const char *name, const char *lib, struct cb_replace_list *replace_list)
{
	struct cb_text_list	*il;
	struct cb_text_list	*el;
	char			*s;
	struct stat		st;

	if (lib) {
		if (!plexbuff1) {
			plexbuff1 = cobc_malloc (COB_SMALL_BUFF);
		}
		snprintf (plexbuff1, COB_SMALL_MAX, "%s/%s", lib, name);
		s = plexbuff1;
	} else {
		s = (char *)name;
	}

	/* Find the file */
	if (stat (s, &st) == 0) {
		return ppopen (s, replace_list);
	}
	if (!plexbuff2) {
		plexbuff2 = cobc_malloc (COB_SMALL_BUFF);
	}
	for (el = cb_extension_list; el; el = el->next) {
		snprintf (plexbuff2, COB_SMALL_MAX, "%s%s", s, el->text);
		if (stat (plexbuff2, &st) == 0) {
			return ppopen (plexbuff2, replace_list);
		}
	}
	if (*s != '/') {
		for (il = cb_include_list; il; il = il->next) {
			for (el = cb_extension_list; el; el = el->next) {
				snprintf (plexbuff2, COB_SMALL_MAX, "%s/%s%s",
					  il->text, name, el->text);
				if (stat (plexbuff2, &st) == 0) {
					return ppopen (plexbuff2, replace_list);
				}
			}
		}
	}
	cb_error (_("%s: %s"), name, strerror (errno));
	return -1;
}

/* Check directives */
/* This is horrible but we have to parse directives directly after the read */
/* as flex buffers up input and it is then too late to use the flex parser */

static void
check_directive (char *buff, int *line_size)
{
	char	*s;
	char	*dirptr;
	size_t	cnt;
	int	n;
	char	sbuff[5][256];

	if (cb_source_format == CB_FORMAT_FIXED) {
		if (*line_size < 8) {
			return;
		}
		if (buff[6] != ' ') {
			return;
		}
		s = &buff[7];
	} else {
		s = buff;
	}
	for (; *s == ' '; s++) {
		;
	}
	dirptr = s;
	if (*s != '>') {
		return;
	}
	s++;
	if (*s != '>') {
		return;
	}
	s++;
	if (*s == 'D') {
		if (cb_flag_debugging_line) {
			memset (dirptr, ' ', 3);
		} else {
			for (cnt = 0; cnt < newline_count; cnt++) {
				buff[cnt] = '\n';
			}
			buff[cnt] = 0;
			strcat (buff, "      *> DEBUG\n");
			*line_size = strlen (buff);
			newline_count = 0;
		}
		return;
	}
	memset (sbuff[0], 0, sizeof (sbuff));
	n = sscanf (s, "%255s %255s %255s %255s %255s",
			sbuff[0], sbuff[1], sbuff[2], sbuff[3], sbuff[4]);
	for (cnt = 0; cnt < newline_count; cnt++) {
		buff[cnt] = '\n';
	}
	buff[cnt] = 0;
	newline_count = 0;
	strcat (buff, "      *> DIRECTIVE\n");
	*line_size = strlen (buff);
	if (n < 2 || strcasecmp (sbuff[0], "SOURCE")) {
		cb_warning (_("Invalid directive - ignored"));
		return;
	}
	switch (n) {
	case 2:
		if (!strcasecmp (sbuff[1], "FIXED")) {
			cb_source_format = CB_FORMAT_FIXED;
			return;
		}
		if (!strcasecmp (sbuff[1], "FREE")) {
			cb_source_format = CB_FORMAT_FREE;
			return;
		}
		if (!strcasecmp (sbuff[1], "FREE_1COL_ASTER")) {
			cb_source_format = CB_FORMAT_FREE_1COL_ASTER;
			cb_source_format1 = 1;
			return;
		}
		break;
	case 3:
		if (strcasecmp (sbuff[1], "FORMAT") &&
		    strcasecmp (sbuff[1], "IS")) {
			break;
		}
		if (!strcasecmp (sbuff[2], "FIXED")) {
			cb_source_format = CB_FORMAT_FIXED;
			return;
		}
		if (!strcasecmp (sbuff[2], "FREE")) {
			cb_source_format = CB_FORMAT_FREE;
			return;
		}
		if (!strcasecmp (sbuff[2], "FREE_1COL_ASTER")) {
			cb_source_format = CB_FORMAT_FREE_1COL_ASTER;
			cb_source_format1 = 1;
			return;
		}
		break;
	default:
		if (strcasecmp (sbuff[1], "FORMAT")) {
			break;
		}
		if (strcasecmp (sbuff[2], "IS")) {
			break;
		}
		if (!strcasecmp (sbuff[3], "FIXED")) {
			cb_source_format = CB_FORMAT_FIXED;
			return;
		}
		if (!strcasecmp (sbuff[3], "FREE")) {
			cb_source_format = CB_FORMAT_FREE;
			return;
		}
		if (!strcasecmp (sbuff[3], "FREE_1COL_ASTER")) {
			cb_source_format = CB_FORMAT_FREE_1COL_ASTER;
			cb_source_format1 = 1;
			return;
		}
		break;
	}
	cb_warning (_("Invalid directive - ignored"));
}

/*
 * Read line
 */

static int
ppinput (char *buff, int max_size)
{

	char	*bp;
	size_t	gotcr;
	size_t	continuation = 0;
	int	ipchar;
	int	i;
	int	n;
	int	coln;
	char	*str1 = NULL;
	char	*str2 = NULL;
	int	j, k;

start:
	/* read a line */
	gotcr = 0;
	ipchar = 0;
	for (n = 0; n < 256 && ipchar != '\n';) {
		ipchar = getc (ppin);
		if (ipchar == EOF) {
			if (n > 0) {
				break;
			}
			if (newline_count == 0) {
				return 0;
			}
			memset (buff, '\n', newline_count);
			buff[newline_count] = 0;
			newline_count = 0;
			return strlen (buff);
		}
		if (n == 0 && cb_source_format != CB_FORMAT_FIXED) {
			if (ipchar != ' ' && ipchar != '\n') {
				buff[n++] = ' ';
			}
		}
		if (gotcr) {
			if (ipchar != '\n') {
				buff[n++] = '\r';
			}
			gotcr = 0;
		}
		if (ipchar == '\r') {
			gotcr = 1;
		} else if (ipchar == '\t') {
			buff[n++] = ' ';
			while (n % cb_tab_width != 0) {
				buff[n++] = ' ';
			}
		} else {
			buff[n++] = ipchar;
		}
	}

	if (buff[n - 1] != '\n') {
		cb_warning (_("Line not terminated by a newline"));
		buff[n++] = '\n';
	}
	buff[n] = 0;

	if ((cb_source_format1 == 1) && ((buff[1] == '*') || (buff[6] == '*'))) {
		newline_count++;
		goto start;
	}

	str1 = strstr (buff, "*>");
	if (str1 != NULL) {
		if ((str1- buff) >= 7) {
			str2 = strstr (str1, "\"");
			if (str2 == NULL) {
				buff[str1-buff] = '\n';
				buff[str1-buff +1] = '\0';
				n = strlen (buff);
			}
		}
	}

	check_directive (buff, &n);

	/* nothing more to do with free format */
	if (cb_source_format != CB_FORMAT_FIXED) {
		return n;
	}

	/* line too short */
	if (n < 8) {
		newline_count++;
		goto start;
	}

	if (cb_flag_mfcomment) {
		if (buff[0] == '*' || buff[0] == '/') {
			newline_count++;
			goto start;
		}
	}
	/* check the indicator (column 7) */
	bp = buff + 7;
	switch (buff[6]) {
	case ' ':
		break;
	case '-':
		continuation = 1;
		break;
	case 'd':
	case 'D':
		/* debugging line */
		if (cb_flag_debugging_line) {
			break;
		}
		newline_count++;
		goto start;
	case '*':
	case '/':
		/* comment line */
		newline_count++;
		goto start;
	default:
		/* invalid indicator */
		cb_error (_("Invalid indicator '%c' at column 7"), buff[6]);
		return YY_NULL;
	}

	/* skip comments that follow after AUTHORS, etc. */
	if (within_comment) {
		/* Check all of "Area A" */
		switch (n) {
		case 8:
			if (buff[7] == ' ') {
				newline_count++;
				goto start;
			}
			break;
		case 9:
			if (!memcmp (&buff[7], "  ", 2)) {
				newline_count++;
				goto start;
			}
			break;
		case 10:
			if (!memcmp (&buff[7], "   ", 3)) {
				newline_count++;
				goto start;
			}
			break;
		default:
			if (!memcmp (&buff[7], "    ", 4)) {
				newline_count++;
				goto start;
			}
			break;
		}
		within_comment = 0;
	}

	/* check the text that is longer than cb_text_column */
	if (n > cb_text_column + 1) {

		/* show warning if it is not whitespaces */
		if (cb_warn_column_overflow && last_line_2 < cb_source_line - 1) {
			for (coln = cb_text_column; coln < n; coln++) {
				if (buff[coln] != ' ' && buff[coln] != '\n') {
					cb_warning (_("Source text after column %d"),
						    cb_text_column);
					break;
				}
			}
		}

		/* remove it */
		strcpy (buff + cb_text_column, "\n");
		last_line_2 = cb_source_line;
		n = cb_text_column + 1;
	}

	/* skip blank lines */
	for (i = 7; buff[i] == ' '; i++) ;
	if (buff[i] == '\n') {
		newline_count++;
		goto start;
	}

	if (continuation) {
		/* line continuation */
		for (; *bp == ' '; bp++) ;

		/* validate concatenation */
		if (consecutive_quotation) {
			if (bp[0] == quotation_mark && bp[1] == quotation_mark) {
				bp++;
			} else {
				cb_error (_("Invalid line continuation"));
				return YY_NULL;
			}
			quotation_mark = 0;
			consecutive_quotation = 0;
		} else if (quotation_mark) {
			/* literal concatenation */
			if (*bp == quotation_mark) {
				bp++;
			} else {
				cb_error (_("Invalid line continuation"));
				return YY_NULL;
			}
		}
	} else {
		/* normal line */
		quotation_mark = 0;
		consecutive_quotation = 0;
	}

	/* check if string literal is to be continued */
	for (i = bp - buff; buff[i] != '\n'; i++) {
		if (buff[i] == '\'' || buff[i] == '\"') {
			if (quotation_mark == 0) {
				/* literal start */
				quotation_mark = buff[i];
			} else if (quotation_mark == buff[i]) {
				if (i == cb_text_column - 1) {
					/* consecutive quotation */
					consecutive_quotation = 1;
				} else {
					/* literal end */
					quotation_mark = 0;
				}
			}
		}
	}

	/* truncate trailing spaces, including the newline */
	if (quotation_mark) {
		for (; i < 72;) {
			buff[i++] = ' ';
		}
		buff[i] = 0;
	} else {
		for (i--; buff[i] == ' '; i--) ;
		if (buff[i] == '\'' || buff[i] == '\"') {
			buff[++i] = ' ';
		}
		buff[i + 1] = 0;
	}

	if (continuation) {
		memmove (buff, bp, strlen (bp) + 1);
		newline_count++;
	} else {
		/* insert newlines at the start of the buffer */
		memmove (buff + newline_count, bp, strlen (bp) + 1);
		memset (buff, '\n', newline_count);
		newline_count = 1;
	}
	return strlen (buff);
}

static void
ppecho (const char *text)
{
	struct cb_replace_list	*r;
	struct cb_text_list	*l;
	struct cb_text_list	*queue;

	if (text_queue == NULL && (text[0] == ' ' || text[0] == '\n')) {
		fputs (text, ppout);
	} else if (!current_replace_list) {
		for (; text_queue; text_queue = text_queue->next) {
			fputs (text_queue->text, ppout);
		}
		fputs (text, ppout);
	} else {
		/* Do replacement */

		text_queue = cb_text_list_add (text_queue, text);

		for (r = current_replace_list; r; r = r->next) {
			queue = text_queue;
			for (l = r->old_text; l; l = l->next) {
				while (l && (l->text[0] == ' ' || l->text[0] == '\n')) {
					l = l->next;
				}
				if (l == NULL) {
					break;
				}
				while (queue && (queue->text[0] == ' ' ||
				       queue->text[0] == '\n')) {
					queue = queue->next;
				}
				if (queue == NULL) {
					return;	/* partial match */
				}
				if (strcasecmp (l->text, queue->text) != 0) {
					break;
				}
				queue = queue->next;
			}
			if (l == NULL) {
				/* match */
				for (l = r->new_text; l; l = l->next) {
					fputs (l->text, ppout);
				}
/*
				text_queue = queue ? queue->next : NULL;
*/
				text_queue = queue;
				continue;
			}
		}

		/* no match */
		for (; text_queue; text_queue = text_queue->next) {
			fputs (text_queue->text, ppout);
		}
	}
}

